language: android
android:
  components:
    - sys-img-armeabi-v7a-android-21
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
install:
  #install adb library
  - sudo pip install adb_android
script:
  - python -m unittest discover
notifications:
    email: false
sudo: false #adaptation to travis's container infrastructure
